#!/usr/bin/env bash
python simulation_mppi.py --dataset snu-asri-ood --predictor socialstgcnn
python simulation_grid.py --dataset snu-asri-ood --predictor socialstgcnn
python simulation_mppi.py --dataset snu-asri --predictor socialstgcnn
python simulation_grid.py --dataset snu-asri --predictor socialstgcnn
python simulation_mppi.py --dataset snu-asri-ood --predictor eigen
python simulation_grid.py --dataset snu-asri-ood --predictor eigen
python simulation_mppi.py --dataset snu-asri --predictor eigen
python simulation_grid.py --dataset snu-asri --predictor eigen
python simulation_mppi.py --dataset snu-asri-ood --predictor koopcast
python simulation_grid.py --dataset snu-asri-ood --predictor koopcast
python simulation_mppi.py --dataset snu-asri --predictor koopcast
python simulation_grid.py --dataset snu-asri --predictor koopcast
python simulation_mppi.py --dataset snu-asri-ood --predictor STGCNN
python simulation_grid.py --dataset snu-asri-ood --predictor STGCNN
python simulation_mppi.py --dataset snu-asri --predictor STGCNN
python simulation_grid.py --dataset snu-asri --predictor STGCNN
python simulation_mppi.py --dataset snu-asri-ood --predictor linear
python simulation_grid.py --dataset snu-asri-ood --predictor linear
python simulation_mppi.py --dataset snu-asri --predictor linear
python simulation_grid.py --dataset snu-asri --predictor linear